### ISSUE TITLE
Link to demo returns 404

### ISSUE THREAD

**Issue by electrik** [triplecanopy/alongslide#3]
Hi
The link to the demo isn't working: https://github.com/triplecanopy/alongslide-demo
Cheers
Matt

**Comment by adamflorin** [comment]
@electrik Just published the repo, please try again. Sorry about that!

**Comment by electrik** [comment]
Thanks! That should make life easier.

**Comment by adamflorin** [comment]
@electrik Yes and feel free to reach out to me directly if you have any questions. adam@canopycanopycanopy.com. Or just make issues here!
